# Generated by Django 4.0 on 2021-12-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email отправителя')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Комментарий отправителя')),
                ('activity_kind', models.CharField(choices=[(None, 'Выберите вид вашей деятельности'), (0, 'Работодатель'), (1, 'Турист')], default='Выберите вид вашей деятельности', max_length=1)),
            ],
        ),
    ]
