# Generated by Django 4.0 on 2021-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_application_activity_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email отправителя')),
                ('provision_kind', models.CharField(choices=[(None, 'Выберите то, что можете предоставить'), ('w', 'Работу'), ('d', 'Работу и проживание'), ('f', 'Работу и еду'), ('a', 'Работу, еду и проживание')], default='Выберите то, что можете предоставить', max_length=1, verbose_name='Обеспечение')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание деятельности')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Комментарий отправителя')),
            ],
            options={
                'verbose_name': 'Заявка работодателя',
                'verbose_name_plural': 'Заявки работодателей',
            },
        ),
        migrations.CreateModel(
            name='TouristApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email отправителя')),
                ('health', models.TextField(max_length=2000, verbose_name='Здоровье отправителя')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание отправителя')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Комментарий отправителя')),
            ],
            options={
                'verbose_name': 'Заявка туриста',
                'verbose_name_plural': 'Заявки туристов',
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
